version: '3.8'

services:
  web:
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 5433:5432
    expose:
      - 8000
    volumes:
      - ./backend:/home/app
      - static_volume:/home/app/static
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  static_volume: